/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leilaocliente.screen;

import base.Cliente;
import base.Produto;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import rmi.ClienteRMI;
import rmi.LeiloeiroInterface;

/**
 *
 * @author Rosana
 */
public class Leilao extends javax.swing.JFrame {

    private boolean registrado;
    private Cliente cliente;
    private ClienteRMI clienteRMI;
    private LeiloeiroInterface leiloeiroInterface;
    private DefaultTableModel model;
    private List<Produto> produtos;
    private int tela;
    private List<Produto> meusProdutos;
    private List<Produto> subscribe;

    /**
     * Creates new form Leilao
     */
    public Leilao() {
        initComponents();

        this.registrado = false;
        this.tela = 1;
        this.meusProdutos = new ArrayList();
        this.subscribe = new ArrayList();

        btnLeiloar.setVisible(false);
        lblTempo.setVisible(false);
        txtTempo.setVisible(false);
        lblDescricao.setVisible(false);
        lblNome.setVisible(false);
        txtNome.setVisible(false);
        lblDescricaoCadastro.setVisible(false);
        txtDescricao.setVisible(false);
        lblPreco.setVisible(false);
        txtPreco.setVisible(false);
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public void setClienteRMI(ClienteRMI clienteRMI) {
        this.clienteRMI = clienteRMI;
    }

    public void setLeiloeiroInterface(LeiloeiroInterface leiloeiroInterface) {
        this.leiloeiroInterface = leiloeiroInterface;
    }

    private void registrarCliente() {
        if (!registrado) {
            try {
                //registrar-se no servidor
                clienteRMI.cadastraCliente(cliente);
                registrado = true;
            } catch (Exception ex) {
                System.out.println("Erro no cadastraCliente");
                ex.printStackTrace();
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLog = new javax.swing.JLabel();
        txtLance = new javax.swing.JTextField();
        lblDescricaoSalao = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblLance = new javax.swing.JLabel();
        btnLance = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        txtTempo = new javax.swing.JTextField();
        btnLeiloar = new javax.swing.JButton();
        txtPreco = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblDescricaoCadastro = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        tblMeusLances = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblSalao = new javax.swing.JLabel();
        lblLeiolar = new javax.swing.JLabel();
        lbMeuslLances = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leilão - Cliente");
        setResizable(false);
        getContentPane().setLayout(null);

        lblLog.setFont(new java.awt.Font("Harrington", 0, 14)); // NOI18N
        lblLog.setForeground(new java.awt.Color(204, 204, 0));
        lblLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLog.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblLog.setAutoscrolls(true);
        lblLog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "~ Log ~", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Harrington", 1, 14), new java.awt.Color(204, 204, 0))); // NOI18N
        lblLog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblLog);
        lblLog.setBounds(40, 370, 250, 340);
        getContentPane().add(txtLance);
        txtLance.setBounds(540, 500, 70, 30);

        lblDescricaoSalao.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        lblDescricaoSalao.setForeground(new java.awt.Color(204, 204, 0));
        lblDescricaoSalao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescricaoSalao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "~ Descrição ~", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Harrington", 1, 14), new java.awt.Color(204, 204, 0))); // NOI18N
        getContentPane().add(lblDescricaoSalao);
        lblDescricaoSalao.setBounds(670, 440, 310, 270);

        lblStatus.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(204, 204, 0));
        lblStatus.setText("Salão de Leilão");
        getContentPane().add(lblStatus);
        lblStatus.setBounds(800, 120, 130, 40);

        lblLance.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        lblLance.setForeground(new java.awt.Color(204, 204, 0));
        lblLance.setText("Valor do Lance:");
        getContentPane().add(lblLance);
        lblLance.setBounds(350, 490, 120, 50);

        btnLance.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        btnLance.setForeground(new java.awt.Color(204, 204, 0));
        btnLance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leilaocliente/imagens/btnLance.jpg"))); // NOI18N
        btnLance.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnLance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLance.setMaximumSize(new java.awt.Dimension(164, 60));
        btnLance.setMinimumSize(new java.awt.Dimension(164, 60));
        btnLance.setPreferredSize(new java.awt.Dimension(164, 60));
        btnLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnLance);
        btnLance.setBounds(400, 580, 164, 60);

        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblClose);
        lblClose.setBounds(1000, 30, 20, 20);

        lblTempo.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        lblTempo.setForeground(new java.awt.Color(204, 204, 0));
        lblTempo.setText("Tempo para Leiolar (min):");
        getContentPane().add(lblTempo);
        lblTempo.setBounds(350, 490, 200, 50);
        getContentPane().add(txtTempo);
        txtTempo.setBounds(540, 500, 70, 30);

        btnLeiloar.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        btnLeiloar.setForeground(new java.awt.Color(204, 204, 0));
        btnLeiloar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leilaocliente/imagens/btnLeiloar.jpg"))); // NOI18N
        btnLeiloar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnLeiloar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeiloar.setMaximumSize(new java.awt.Dimension(164, 60));
        btnLeiloar.setMinimumSize(new java.awt.Dimension(164, 60));
        btnLeiloar.setPreferredSize(new java.awt.Dimension(164, 60));
        btnLeiloar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeiloarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeiloar);
        btnLeiloar.setBounds(510, 580, 164, 60);
        getContentPane().add(txtPreco);
        txtPreco.setBounds(910, 270, 60, 30);

        lblPreco.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(204, 204, 0));
        lblPreco.setText("Preço");
        getContentPane().add(lblPreco);
        lblPreco.setBounds(920, 190, 50, 50);
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(560, 270, 250, 30);

        lblDescricaoCadastro.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        lblDescricaoCadastro.setForeground(new java.awt.Color(204, 204, 0));
        lblDescricaoCadastro.setText("Descrição");
        getContentPane().add(lblDescricaoCadastro);
        lblDescricaoCadastro.setBounds(630, 190, 90, 50);
        getContentPane().add(txtNome);
        txtNome.setBounds(350, 270, 150, 30);

        lblNome.setFont(new java.awt.Font("Harrington", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(204, 204, 0));
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(390, 190, 50, 50);

        lblDescricao.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(204, 204, 0));
        lblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "~ Descrição ~", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Harrington", 1, 14), new java.awt.Color(204, 204, 0))); // NOI18N
        getContentPane().add(lblDescricao);
        lblDescricao.setBounds(300, 440, 690, 270);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        tblMeusLances.setViewportView(jTable1);

        getContentPane().add(tblMeusLances);
        tblMeusLances.setBounds(310, 190, 670, 180);

        lblSalao.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        lblSalao.setForeground(new java.awt.Color(204, 204, 0));
        lblSalao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalao.setText("Salão de Leilão");
        lblSalao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalaoMouseClicked(evt);
            }
        });
        getContentPane().add(lblSalao);
        lblSalao.setBounds(50, 310, 240, 60);

        lblLeiolar.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        lblLeiolar.setForeground(new java.awt.Color(204, 204, 0));
        lblLeiolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLeiolar.setText("Leiloar");
        lblLeiolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLeiolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeiolarMouseClicked(evt);
            }
        });
        getContentPane().add(lblLeiolar);
        lblLeiolar.setBounds(50, 240, 240, 60);

        lbMeuslLances.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        lbMeuslLances.setForeground(new java.awt.Color(204, 204, 0));
        lbMeuslLances.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMeuslLances.setText("Meus Lances");
        lbMeuslLances.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMeuslLances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMeuslLancesMouseClicked(evt);
            }
        });
        getContentPane().add(lbMeuslLances);
        lbMeuslLances.setBounds(40, 170, 240, 60);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leilaocliente/imagens/leilaoCliente.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1070, 730);

        setSize(new java.awt.Dimension(1043, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeiloarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeiloarActionPerformed
        System.out.println("Leiloar");
        registrarCliente();

        String nome = txtNome.getText();
        String descricao = txtDescricao.getText();
        String precoString = txtPreco.getText();
        precoString = precoString.replace(",", ".");
        double preco = Double.parseDouble(precoString);
        int tempo = Integer.parseInt(txtTempo.getText());

        Produto produto = new Produto(nome, descricao, preco, tempo, cliente.getId());

        try {
            leiloeiroInterface.incluirProduto(produto);
        } catch (RemoteException ex) {
            Logger.getLogger(Leilao.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNome.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        txtTempo.setText("");

        lblLog.setText(lblLog.getText() + "Produto inserido no servidor");
    }//GEN-LAST:event_btnLeiloarActionPerformed

    private void btnLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanceActionPerformed
        registrarCliente();

        //dar lance num produto
        int linha = jTable1.getSelectedRow();
        if (produtos.get(linha).getClienteID() != cliente.getId() && produtos.get(linha).getLanceID() != cliente.getId()) {

            String precoString = txtLance.getText();
            precoString = precoString.replace(",", ".");
            double preco = Double.parseDouble(precoString);
            try {
                leiloeiroInterface.lance(produtos.get(linha).getID(), preco, cliente.getId(), clienteRMI.getClienteInterface());
            } catch (RemoteException ex) {
                System.out.println("Erro em dar lance");
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operação não pode ser realizada. Esse produto é seu ou o último lance é seu!", "ALERTA", JOptionPane.WARNING_MESSAGE);
        }
        
        txtLance.setText("");
        atualizarSalaoLeilao();
    }//GEN-LAST:event_btnLanceActionPerformed

    private void lbMeuslLancesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMeuslLancesMouseClicked
        tela = 3;
        lblStatus.setText("Meus Lances");

        tblMeusLances.setVisible(true);
        lblDescricao.setVisible(true);

        txtDescricao.setVisible(false);
        lblNome.setVisible(false);
        txtNome.setVisible(false);
        lblDescricaoCadastro.setVisible(false);
        lblPreco.setVisible(false);
        txtPreco.setVisible(false);
        lblLance.setVisible(false);
        txtLance.setVisible(false);
        lblTempo.setVisible(false);
        txtTempo.setVisible(false);
        btnLance.setVisible(false);
        btnLeiloar.setVisible(false);
        lblDescricaoSalao.setVisible(false);

        meusProdutos = new ArrayList();
        subscribe = new ArrayList();

        //buscar primeiro os meus produtos
        try {
            meusProdutos = leiloeiroInterface.meusProdutos(cliente.getId());

            //buscar produtos de meu interesse
        } catch (RemoteException ex) {
            System.out.println("Erro no buscar meus produtos");
            ex.printStackTrace();
        }

        //buscar produtos do subscribe
        try {
            subscribe = leiloeiroInterface.produtosSubscribe(cliente.getId());

            //buscar produtos de meu interesse
        } catch (RemoteException ex) {
            System.out.println("Erro no buscar meus subscribes");
            ex.printStackTrace();
        }

        if (model != null) {
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        }

        model = (DefaultTableModel) jTable1.getModel();

        String[] linha;
        for (Produto p : meusProdutos) {
            linha = new String[]{Integer.toString(p.getID()), p.getNome(), Double.toString(p.getLance())};
            model.addRow(linha);
        }
        linha = new String[]{"SUBSCRIBES", "-----", "----"};
        model.addRow(linha);

        for (Produto p : subscribe) {
            linha = new String[]{Integer.toString(p.getID()), p.getNome(), Double.toString(p.getLance())};
            model.addRow(linha);
        }
    }//GEN-LAST:event_lbMeuslLancesMouseClicked

    private void lblLeiolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeiolarMouseClicked
        tela = 2;
        lblStatus.setText("Leiloar");
        lblNome.setVisible(true);
        txtNome.setVisible(true);
        lblDescricaoCadastro.setVisible(true);
        txtDescricao.setVisible(true);
        lblPreco.setVisible(true);
        txtPreco.setVisible(true);
        lblLance.setVisible(true);
        txtLance.setVisible(true);
        lblTempo.setVisible(true);
        txtTempo.setVisible(true);
        btnLeiloar.setVisible(true);

        tblMeusLances.setVisible(false);
        lblDescricao.setVisible(false);
        txtLance.setVisible(false);
        lblLance.setVisible(false);
        lblDescricaoSalao.setVisible(false);
        btnLance.setVisible(false);

    }//GEN-LAST:event_lblLeiolarMouseClicked

    private void lblSalaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalaoMouseClicked

        tela = 1;
        lblStatus.setText("Salão de Leilão");

        tblMeusLances.setVisible(true);
        btnLance.setVisible(true);
        lblLance.setVisible(true);
        txtLance.setVisible(true);
        lblDescricaoSalao.setVisible(true);

        lblTempo.setVisible(false);
        txtTempo.setVisible(false);
        btnLeiloar.setVisible(false);
        lblTempo.setVisible(false);
        txtTempo.setVisible(false);
        lblDescricao.setVisible(false);
        lblNome.setVisible(false);
        txtNome.setVisible(false);
        lblDescricaoCadastro.setVisible(false);
        txtDescricao.setVisible(false);
        lblPreco.setVisible(false);
        txtPreco.setVisible(false);

        System.out.println("Salão de leilão");

        atualizarSalaoLeilao();
    }//GEN-LAST:event_lblSalaoMouseClicked

    private void atualizarSalaoLeilao() {
        produtos = new ArrayList();
        try {
            //buscar produtos à venda
            produtos = leiloeiroInterface.listaProdutos();
        } catch (RemoteException ex) {
            System.out.println("Erro no buscar lista de produtos à venda");
            ex.printStackTrace();
        }

        if (model != null) {
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
        }

        model = (DefaultTableModel) jTable1.getModel();

        for (Produto p : produtos) {
            String[] linha = new String[]{Integer.toString(p.getID()), p.getNome(), Double.toString(p.getLance())};
            model.addRow(linha);
        }
    }


    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        
        int linha = jTable1.getSelectedRow();
        System.out.println("tela: "+tela);
        System.out.println("linha: "+linha);
        if (tela == 1) {
            lblDescricaoSalao.setText(produtos.get(linha).getDescricao());
        } else if (tela == 3) {
            if (linha < meusProdutos.size()) {
                lblDescricao.setText(meusProdutos.get(linha).getDescricao());
            } else if (linha > meusProdutos.size()) {
                lblDescricao.setText(subscribe.get(linha - meusProdutos.size() - 1).getDescricao());
            }
            else{
                lblDescricao.setText("");
            }
                
        }

    }//GEN-LAST:event_jTable1MouseClicked

    public void adicionarLog(String log) {
        lblLog.setText(lblLog.getText() + "\n" + log);
        if (tela == 1) {
            atualizarSalaoLeilao();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leilao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leilao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leilao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leilao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leilao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLance;
    private javax.swing.JButton btnLeiloar;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbMeuslLances;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricaoCadastro;
    private javax.swing.JLabel lblDescricaoSalao;
    private javax.swing.JLabel lblLance;
    private javax.swing.JLabel lblLeiolar;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblSalao;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JScrollPane tblMeusLances;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtLance;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables
}
